### ISSUE TITLE
Relationship order

### ISSUE THREAD

**Issue by aleene** [chriscdn/RHManagedObject#23]
I planned to use the ordered relationship arrangement in the cored data data model. I wanted to be able to reorder in a tableview. I order to save the new order in the database one has to make a NSMutableOrderedSet, implement the changes and save back to the NSOrderedSet of the database. This works as planned and is saved in the right way by logging the description of the NSOrderedSet.

However when reading the set with RHManaged FetchAll, the order seems lost. It seems that the FetchAll does not take into account the order of the relationship and default to the original order.

I guess that this is now a bug, due to the change that Apple made to Core Data when they introduced this order feature.

**Comment by aleene** [comment]
I solved it by not using the RHManagedObject library, but instead using the relationship attribute on the Cored Data object.

**Comment by chriscdn** [comment]
@aleene: I don't believe this is a bug since `fetchAll` isn't meant to be used to follow a relationship among entities.  The `fetchAll` method is there for getting all instances of an entity.

**Comment by aleene** [comment]
OK, I just was not aware of this issue.
